import {
  pgTable,
  serial,
  integer,
  text,
  boolean,
  timestamp,
  date,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";
import { candidatesTable } from "./candidates";
import { applicationsTable } from "./applications";
import { usersTable } from "./auth";

/**
 * Saved job-search queries created by candidates from the /jobs page.
 * Stores the structured filters (search text + job type) plus a name
 * the candidate gave the search and an opt-in alerts flag. The
 * `lastSeenJobId` lets the daily alert worker emit only new matches
 * (any job with id > lastSeenJobId that still satisfies the filters).
 */
export const candidateSavedSearchesTable = pgTable(
  "candidate_saved_searches",
  {
    id: serial("id").primaryKey(),
    candidateId: integer("candidate_id")
      .notNull()
      .references(() => candidatesTable.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    searchText: text("search_text"),
    jobType: text("job_type"),
    /** Full UI query state (filters + sort) as JSON, so saved searches can
     *  round-trip every facet the jobs page exposes — not just the two
     *  fields we project out for the alert-matching SQL. */
    filtersJson: text("filters_json").notNull().default("{}"),
    sortBy: text("sort_by"),
    /** Per-channel alert preferences. `alertsEnabled` is kept as a
     *  legacy mirror for older clients, derived as (email OR inApp). */
    emailAlerts: boolean("email_alerts").notNull().default(true),
    inAppAlerts: boolean("in_app_alerts").notNull().default(true),
    alertsEnabled: boolean("alerts_enabled").notNull().default(true),
    lastSeenJobId: integer("last_seen_job_id").notNull().default(0),
    lastAlertedAt: timestamp("last_alerted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    savedSearchCandIdx: index("saved_search_cand_idx").on(t.candidateId),
  }),
);

export type CandidateSavedSearch =
  typeof candidateSavedSearchesTable.$inferSelect;
export type InsertCandidateSavedSearch =
  typeof candidateSavedSearchesTable.$inferInsert;

/**
 * Append-only history of application status transitions. The first row
 * for an application is its initial "applied" event; each subsequent
 * PATCH /applications/:id appends one row. Powers the milestone
 * timeline on the candidate-side application detail view.
 *
 * Older applications (created before this table existed) won't have a
 * full history — the timeline UI back-fills the implied "applied"
 * milestone from `applications.appliedAt` and the most recent status
 * from `applications.updatedAt` so the chart is never empty.
 */
export const applicationStatusHistoryTable = pgTable(
  "application_status_history",
  {
    id: serial("id").primaryKey(),
    applicationId: integer("application_id")
      .notNull()
      .references(() => applicationsTable.id, { onDelete: "cascade" }),
    status: text("status").notNull(),
    changedAt: timestamp("changed_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    changedBy: integer("changed_by").references(() => usersTable.id, {
      onDelete: "set null",
    }),
  },
  (t) => ({
    appHistoryAppIdx: index("app_history_app_idx").on(
      t.applicationId,
      t.changedAt,
    ),
  }),
);

export type ApplicationStatusHistory =
  typeof applicationStatusHistoryTable.$inferSelect;

/**
 * One row per (candidate, weekStart). Generated by the digest worker
 * every Monday at 00:00 UTC; surfaced in the candidate dashboard +
 * mobile home as a "Your week" card and (eventually) emailed via the
 * existing email helper. `newMatchesJson` is a JSON-encoded array of
 * `{jobId, title, employerName, matchScore}` precomputed at digest
 * time so the card renders instantly without re-running the matcher.
 */
export const candidateWeeklyDigestsTable = pgTable(
  "candidate_weekly_digests",
  {
    id: serial("id").primaryKey(),
    candidateId: integer("candidate_id")
      .notNull()
      .references(() => candidatesTable.id, { onDelete: "cascade" }),
    weekStart: date("week_start").notNull(),
    profileViews: integer("profile_views").notNull().default(0),
    applicationsSent: integer("applications_sent").notNull().default(0),
    interviewsScheduled: integer("interviews_scheduled").notNull().default(0),
    newMatchesJson: text("new_matches_json").notNull().default("[]"),
    generatedAt: timestamp("generated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** Set when the email helper successfully hands off to a provider.
     *  Stays NULL when the provider is not configured (current
     *  default), so we can later replay digests that were generated
     *  but not yet emailed. */
    emailSentAt: timestamp("email_sent_at", { withTimezone: true }),
    emailSendResult: text("email_send_result"),
  },
  (t) => ({
    weeklyDigestUnique: uniqueIndex("weekly_digest_unique").on(
      t.candidateId,
      t.weekStart,
    ),
  }),
);

export type CandidateWeeklyDigest =
  typeof candidateWeeklyDigestsTable.$inferSelect;
export type InsertCandidateWeeklyDigest =
  typeof candidateWeeklyDigestsTable.$inferInsert;
